### PR TITLE
Standardize sample projects, Part 3

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Comment by nxtn** [comment]
> D:\a\samples\samples\core\console-apps\NewTypesMsBuild\src\NewTypes\NewTypes.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 3.1.11)
> D:\a\samples\samples\csharp\getting-started\console-webapiclient\webapiclient.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 3.1.11)

There isn't .NET Core 3.1.11. The latest version of .NET Core is 3.1.10.

**Comment by RussKie** [comment]
It's trying to pull a non-public package for some reason.

@Thraka  any ideas?

**Comment by BillWagner** [comment]
closing and reopening for a fresh build.

The build error may have been addressed by updating internal and public Nuget feeds.

**Comment by adegeo** [comment]
Found this lost in my notifications. We've done a few modifications to the samples testing system, you'll need to rebase your PR and reopen it. I'll close for now.

**Pull request closed without merging**
