### PR TITLE
Remove trailing spaces, Part 1

### PR DESCRIPTION
**Pull request by NextTurn**
Enforces [SA1028](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md).

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @NextTurn. There are a few merge conflicts now.

**Comment by NextTurn** [comment]
I see. Caused by #1935.

**Comment by NextTurn** [comment]
@BillWagner Used a regex this time. ` +$`

**Comment by Thraka** [comment]
Closing this. I've copied the existing snippets folder into the dotnet/docs repo. API repo is the next to be worked on, then the snippets folder will be deleted from here. With this big changes going on, and trying to keep the snippets folder in sync as much as possible, I don't want any changes to those files.

**Pull request closed without merging**
