### PR TITLE
Array.xml samples -- updating for Try .NET

### PR DESCRIPTION
**Pull request by WilliamAntonRohm**
docs PR is https://github.com/dotnet/dotnet-api-docs/pull/3463

### CODE REVIEW

**Comment by WilliamAntonRohm** [comment]
@mairaw, @BillWagner -- in addition to these two samples, there are 98 more in Array.xml.  Please let me know if I should pursue those as well.

**Comment by mairaw** [comment]
98?? I think we should wait for the scaffolding feature that is coming in a few weeks.

**Comment by mairaw** [comment]
Second sample looks good but I'm not sure if we want to change the function names in order to make the sample work with interactive that way.

**Comment by WilliamAntonRohm** [comment]
@mairaw -- I'll revert the second sample -- currently Try .NET doesn't compile overloaded functions.

**Comment by WilliamAntonRohm** [comment]
@mairaw -- D'oh!  I thought I already had.  I just now reverted source.cs to the original and I believe this PR is ready to merge.

**Pull request merged**
