### PR TITLE
Port Windows Forms Samples to VB

### PR DESCRIPTION
**Pull request by paul1956**
## Summary
Port WindowsForms/Graphics from C# to VB Core 3.0
Describe your changes here.
Ported code, updated comments added VB Project to existing solution
Fixes dotnet/docs#Issue_Number or dotnet/dotnet-api-docs#Issue_Number (if available)

### CODE REVIEW

**Comment by paul1956** [comment]
Is there a way to get the original .gitignore file and add it back?

**Comment by rpetrusha** [comment]
Yes. Try this:
1. Change to your master branch (`git checkout master`).
2. Copy the .gitignore file to a temporary directory.
3. Change to your GitWinFormGraphicsVb branch (`git checkout GitWinFormGraphicsVb`)
4. Replace .gitignore with the file from the temporary directory.

If that doesn't work, rebase your master branch:
1, `git checkout master`
2. `git remote -add upstream https://gitHub.com/dotnet/samples`
3.  `git fetch upstream`
4. `git rebase upstream/master`
5. `git push -f`
That gets the current .gitignore into your master branch. Then you can follow the steps above to get it into the GitWinFormGraphicsVb branch. When you commit your changes, that should remove it from the PR.

**Comment by paul1956** [comment]
I think I did it using the first instruction.

**Comment by rpetrusha** [comment]
Thanks, @paul1956. The .gitignore file has some inconsequential differences, and I've fixed a merge conflict involving three files, so this is ready to merge. Thanks for your patience.

**Pull request merged**
