### PR TITLE
removing sample

### PR DESCRIPTION
**Pull request by mairaw**
Related to  dotnet/docs#5200 and #47

### CODE REVIEW

**Comment by pkulikov** [comment]
@mairaw thank you for the fix.

In general, the following pattern of dealing with two repos looks workable:
- PR to dotnet/samples that doesn't break the dotnet/docs master and supports related PR there. Review and merge it.
- Review and merge related PR in dotnet/docs
- Make one more PR to dotnet/samples to remove obsolete source code.

**Comment by rpetrusha** [comment]
Merge conflicts seem to be happening with regularity, @BillWagner, for all PRs in this repo. I'm not sure why.

**Comment by pkulikov** [comment]
That might be merged now as dotnet/docs#5200 is merged.

**Comment by mairaw** [comment]
The merge conflict happened because the dependent PRs were not merged at the same time @BillWagner @rpetrusha.

**Pull request merged**
