### PR TITLE
Delete unused snippets

### PR DESCRIPTION
**Pull request by Youssef1313**
Contributes to https://github.com/dotnet/docs/issues/14825

Addressed the first 16 records in Ron's utility [output](https://gist.github.com/rpetrusha/1485cccf2fa72b1bbac40d24a9c594e5).

I've manually checked the deleted files aren't referenced anywhere. **but** I prefer that you re-check again and don't depend on me and the utility.

**Note:** If I'm not mistaken, I caught one false positive in the output as stated in https://github.com/dotnet/docs/issues/14825#issuecomment-5540204080. (that's why it's important to re-check the deleted samples)

### CODE REVIEW

**Comment by Thraka** [comment]
There are only about 130 references to the "VS_Snippets_Atlas" folder in the api docs repo. None of the files on this list were there.

There were 0 references to the "VS_Snippets_Atlas" folder in the dotnet docs repo.

There were 0 references to the "VS_Snippets_Atlas" folder in the aspnetcore docs.

**Comment by mairaw** [comment]
I don't think that we'll need those. This is a bit of a migration leftover as well because in the previous system we had all of the different folders (CS, VB, common) under a single folder and here they are split because we thought it would be easier to set up different CI systems that way. They would probably be helpful if something is trying to have the whole project put together but they are probably not referenced from docs.

**Comment by Youssef1313** [comment]
@thraka, @mairaw, I'm not sure how a usage of one of the files was missed.

https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.UI/ScriptManager.xml#L2313

Where should this file be moved ?
It also will be good if someone can revise Ron's tool and fix those false positive.

**Comment by Youssef1313** [comment]
Is there anything left for this ?

**Comment by Youssef1313** [comment]
Ping @mairaw @BillWagner

**Comment by BillWagner** [comment]
I'll merge this and watch upcoming builds to see if there are any known issues.

**Pull request merged**
