### PR TITLE
Add parent cs folders to the paths of all the samples used in the Json-DateTime doc

### PR DESCRIPTION
**Pull request by layomia**
Addresses https://github.com/dotnet/samples/pull/1412#issuecomment-528105208.
Used in https://github.com/dotnet/docs/pull/14056/commits/3a082aa14f4b5269977240205af7a7ce0d80feac.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Why did we decide to call all the cs files Program.cs and move the name to a folder instead?

cc @mairaw, @rpetrusha

**Comment by rpetrusha** [comment]
Having csharp files in a cs directory allows for multiple languages to share the same parent directory (for example, we can now add a vb directory for a vb example). It also allows the language of the example to be readily determined without having to look at file extensions, and is useful for CI tools.

**Comment by ahsonkhan** [comment]
> Having csharp files in a cs directory allows for multiple languages to share the same parent directory (for example, we can now add a vb directory for a vb example). It also allows the language of the example to be readily determined without having to look at file extensions, and is useful for CI tools.

I understand that we want to have language specific sub-directories.

However, this PR is changing the file names too:

snippets/standard/datetime/json/computing-with-jsondocument-error.cs → snippets/standard/datetime/json/computing-with-jsondocument-error/cs/Program.cs

How about something like this rather than calling them all `Program.cs` within a directory that contains the name? We can still have the `cs` subdirectory.
snippets/standard/datetime/json/cs/computing-with-jsondocument-error.cs

**Comment by layomia** [comment]
@rpetrusha 

> Are you planning to submit a PR that changes the path to the samples where they're used in the docs repo?

Yes, https://github.com/dotnet/docs/pull/14056 changes the paths.

Can you please advise on the correct path structure, i.e.

snippets/standard/datetime/json/computing-with-jsondocument-error/cs/Program.cs (current), versus
snippets/standard/datetime/json/cs/computing-with-jsondocument-error.cs,

and also the correct directory to place these samples, re @ahsonkhan's comment: https://github.com/dotnet/samples/pull/1418#issuecomment-528641741.

**Comment by ahsonkhan** [comment]
@rpetrusha - any updates on this? If it makes no difference, I am fine with the current changes as is. I'd like to get this merged.

**Comment by mairaw** [comment]
As I mentioned in the previous PR where we discussed this, I think the folder name should be csharp, so it matches the language identifier and other paths where we've been using this:

e.g. 
https://github.com/dotnet/samples/tree/master/csharp
https://github.com/dotnet/samples/tree/master/snippets/csharp
https://github.com/dotnet/samples/tree/master/snippets/standard/base-types/format-strings/csharp

Thoughts?

**Comment by ahsonkhan** [comment]
Seems reasonable to me. For example, I would be fine with the following layout:
https://github.com/dotnet/samples/tree/master/snippets/standard/datetime/json/csharp/computing-with-jsondocument-error/Program.cs
https://github.com/dotnet/samples/tree/master/snippets/standard/datetime/json/csharp/datetime-converter-examples/example1/Program.cs
etc.

**Pull request merged**
