### PR TITLE
fix: Unscore XML and missed csharp "astoria" files

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@rpetrusha I think this should be the rest. There are some in the "cpp" folder, but I think that would be something to change with the cpp-docs repo separately

**Comment by mairaw** [comment]
Not sure if the cpp docs are using the samples from here. The .NET content does have C++ examples too.

**Comment by nschonni** [comment]
I didn't see any of the cpp versions in the build warnings. It's possible they're orphans if the cpp-docs isn't using them. I didn't go looking in those docs for references though

**Comment by mairaw** [comment]
Ok. Let's merge this and see if we get any warnings. It'd be good to clean up this repo as well at some point and remove unused samples. Oh well...

**Pull request merged**
