### PR TITLE
Create Join operation example for CS LINQ

### PR DESCRIPTION
**Pull request by SuperNova911**
CsLINQ Join, GroupJoin examples

Fixes dotnet/docs#16237

### CODE REVIEW

**Comment by Youssef1313** [comment]
Better to include a csproj file, I think. You may wait until @BillWagner or @mairaw confirm that.

**Comment by BillWagner** [comment]
Ping @SuperNova911  Can you add the csproj file for this new sample? Thanks.

**Comment by Youssef1313** [comment]
@BillWagner, I think this one needs to be re-opened and merged

**Comment by BillWagner** [comment]
Great catch @Youssef1313  (the commit message accidentally closed this)

**Pull request merged**
