### PR TITLE
Update guid samples

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by BillWagner** [comment]
@Youssef1313 I'm closing this PR. As I said https://github.com/dotnet/samples/pull/1654#discussion_r337670053 the methods `Guid.NewGuid` and `Guid.Parse` are clearly named factory methods that return a `Guid`. That is clear to most readers, and the use of `var` is fine.

The guideline of "its use is clear" is somewhat subjective. In this instance, I asked a few colleagues for their opinion, and we all agree that this use is clear.

**Comment by Youssef1313** [comment]
@BillWagner, Actually one of the changes made was to use `var`.

For the other changes:
My understanding of using var when the type is "obvious" is that it's obvious by a C# language rule. Like `Guid x = new Guid(..);`.
I think @stephentoub may confirm what's exactly meant by "obvious" and he may update the style guide in corefx repo to make it more clearer.

**Comment by stephentoub** [comment]
> I think @stephentoub may confirm what's exactly meant by "obvious"

An explicit cast `(T)` or a `new T(...)`.

**Comment by mairaw** [comment]
So your recommendation would be to reopen this and accept the changes, correct @stephentoub?

**Comment by stephentoub** [comment]
Personally I like the change, and it better conforms to the style guidelines we have for code in corefx (which we don't conform to 100%, but we're incrementally getting there).  That said, everyone has their own style and opinions.  The more important thing is that the docs are internally self-consistent, whatever style it settles on.

**Comment by BillWagner** [comment]
Thanks for clarifying @stephentoub. I was hasty in closing this. 

Whether or not to use `var` is one of the more controversial guidelines. There are analyzers that convert to var, and analyzers that convert to an explicit team. They are both very popular. 

My main concern is to avoid repeated changes that add var / remove var and so on. Historically, we've avoided that. 

I"ll reopen and merge this.

**Pull request merged**
