### PR TITLE
Update HostingWithHostFxr to 3.1

### PR DESCRIPTION
**Pull request by vitek-karas**
Also small changes to the readme

### CODE REVIEW

**Comment by vitek-karas** [comment]
The failure occurs because this sample requires native compilers to be available (C++ compiler) on the machine and for the build to run from Visual Studio Developer environment (so that the compilers are accessible).

I guess this won't work in the CI build system - is there a way to tell the CI to not build a specific project?

**Comment by adegeo** [comment]
Add a file named snippets.5000.json as peer to the solution file you want to compile with visual studio and put this inside of it:

```json
{
    "host": "visualstudio"
}

```

This forces the build system to run the vs dev prompt and msbuild instead of dotnet.

**Review by elinor-fung — COMMENTED** [review]
The other complication for the build is that, since we use the bitness of `dotnet` to find the corresponding `nethost` lib, we need the bitness of the native compiler to match that of `dotnet` - and the normal VS developer command prompt has the 32-bit native compiler.

We could also try switching it to find the compiler automatically on Windows - similar to what the `IDynamicCastableInterface` (https://github.com/dotnet/samples/pull/3744/commits/82748ddeb041b936c45b94eb620a8548feabcf70) and p/invoke marshalling (https://github.com/dotnet/samples/commit/3bbeef4a3ed0ee95cd0da3465cb3d91a393731cb) samples do.

**Comment by adegeo** [comment]
How much config changes do you expect users to do when they download the sample?

**Comment by vitek-karas** [comment]
Ideally none - it should just work.
I'm following @elinor-fung advice and porting over the native build from the marshalling sample. That should be buildable without issues and without environment (basically the same as marshalling sample)

**Comment by vitek-karas** [comment]
Finally reworked it so that it should not need any special treatment. Works both from command line and VS, also works on Linux.
Ready for review.

**Review by BillWagner — APPROVED** [review]
This LGTM @vitek-karas 

I'll :shipit: now.

**Pull request merged**
