### PR TITLE
Fix compilation

### PR DESCRIPTION
**Pull request by thaystg**
It was targetting .net7 and using a package 8.0.0 it was causing a compilation error.

` error NU1202: Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 8.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 8.0.0 supports: net8.0 (.NETCoreApp,Version=v8.0) [S:\diagnostics\4170\samples\core\diagnostics\DiagnosticScenarios\DiagnosticScenarios.csproj]`

### CODE REVIEW

**Review by noahfalk — APPROVED** [review]
👍

**Comment by gewarren** [comment]
@thaystg For some reason you're showing as an external contributor and it wants you to sign the license. Have you linked your GitHub and Microsoft accounts? https://review.learn.microsoft.com/en-us/help/get-started/setup-github?branch=main#2-link-your-github-and-microsoft-accounts

**Comment by thaystg** [comment]
> @thaystg For some reason you're showing as an external contributor and it wants you to sign the license. Have you linked your GitHub and Microsoft accounts? https://review.learn.microsoft.com/en-us/help/get-started/setup-github?branch=main#2-link-your-github-and-microsoft-accounts

Yes, they are linked. Accessing that link I saw that they are already linked. Not sure what else I should do.

image

**Comment by thaystg** [comment]
Thanks, can I merge?

**Pull request merged**
