### PR TITLE
do not deploy extension on build

### PR DESCRIPTION
**Pull request by jmarolf**
## Summary

Describe your changes here.

Fixes #Issue_Number, dotnet/docs#Issue_Number or dotnet/dotnet-api-docs#Issue_Number (if available)

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
I like this.

I'll :shipit: now.

**Comment by BillWagner** [comment]
@Youssef1313 Let me know if you want to update the project files for other roslyn samples, or if you want me to do that.

**Comment by Youssef1313** [comment]
@BillWagner for dotnet/docs I opened. https://github.com/dotnet/docs/pull/24302

Not sure if this should be done in dotnet/roslyn-sdk.

**Comment by BillWagner** [comment]
@Youssef1313 

> Not sure if this should be done in dotnet/roslyn-sdk.

You should ask that question on that repo. I don't know.

**Pull request merged**
