### PR TITLE
Clean up try..catch with System.Exception

### PR DESCRIPTION
**Pull request by Mackiovello**
**Not ready to be merged yet**

Takes care of these:
- snippets\csharp\VS_Snippets_CLR\AccessControl.FileSystemAuditRule\cs\sample.cs
- snippets\csharp\VS_Snippets_CLR\aescryptoservprovider\cs\program.cs
- snippets\csharp\VS_Snippets_CLR\aesmanaged\cs\program.cs
- snippets\csharp\VS_Snippets_CLR\aessample\cs\program.cs

For https://github.com/dotnet/docs/issues/4870

### CODE REVIEW

**Comment by BillWagner** [comment]
@Mackiovello I see you've put the WIP label on this PR. Are you ready for an initial review? Let us know when you are ready, and we'll give it a look.

**Comment by Mackiovello** [comment]
> @Mackiovello I see you've put the WIP label on this PR. Are you ready for an initial review? 

I want to look over this one once more before review. I'll give you a ping when I'm ready.

**Comment by Mackiovello** [comment]
Okay, I think this is right. @BillWagner it's ready for you to take a look

**Comment by Mackiovello** [comment]
Thanks @rpetrusha! I removed the `Imports System` statements in https://github.com/dotnet/samples/pull/409/commits/6ebf45ee191bfd90936cfaaa5e3f9765cc2ae6ca

**Comment by rpetrusha** [comment]
This looks great, @Mackiovello. I'll merge your PR now.

**Pull request merged**
