### PR TITLE
restore missing file

### PR DESCRIPTION
**Pull request by BillWagner**
Somehow, this was removed from #1876

Thanks for catching this @tdykstra

### CODE REVIEW

**Comment by Youssef1313** [comment]
The docs PR mentions the file being in `snippets/csharp/VS_Snippets_VBCSharp/CsLINQJoin/CS/` not in `snippets/csharp/VS_Snippets_VBCSharp/`. And I see it already exists in the correct place.

**Comment by Youssef1313** [comment]
The reason it doesn't appear in docs (in my opinion) is that master isn't merged to live yet.

**Comment by BillWagner** [comment]
@mairaw  I made this one while traveling after @tdykstra alerted me to the warnings.

If the original commit was found / merged, this can just be closed. 

I'll close, and if this is needed we can reopen.

**Comment by mairaw** [comment]
I'm still trying to figure out what's wrong. The bad snippet reference makes no sense to me.

**Comment by Youssef1313** [comment]
@mairaw, I think I found it!
Two folders with the same name exists under different casing

**Comment by mairaw** [comment]
Yep I came to the same conclusion and opened a PR already.

**Pull request closed without merging**
