### PR TITLE
Fix property sample coding  conventions

### PR DESCRIPTION
**Pull request by rumaniel**
I saw the MSDN pages about properties and found that there is another [sample coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties).
Other property page samples don't have `_` prefix but that page has.
So I fix the conventions as other samples.

### CODE REVIEW

**Comment by BillWagner** [comment]
Thanks for making this update @rumaniel 

Before I merge this, can you make a related PR in dotnet/docs to update the reference to the `seconds` field. The article on [properties](https://github.com/dotnet/docs/blame/master/docs/csharp/programming-guide/classes-and-structs/properties.md#L31) would need one change.

It's important that we keep the article and the sample in sync.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

> We use _camelCase for internal and private fields and use readonly where possible. Prefix internal and private instance fields with _, static fields with s_ and thread static fields with t_. When used on static fields, readonly should come after static (e.g. static readonly not readonly static). Public fields should be used sparingly and should use PascalCasing with no prefix when used.

**Comment by rumaniel** [comment]
Yes, there is no wrong convention. But I want to match the convention of [the overview article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties) and other property articles([using](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties), [interface](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/interface-properties) and [restricting accessor](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility)).

So how about modifying other 3 articles?

**Comment by BillWagner** [comment]
This is a great conversation.  I'll propose the following guidelines:

1. Most important, any variable changes should be checked with the articles where a sample is included to make sure they match after the change. Especially for readers learning the language, those details matter for the learning experience.
1. If we do make variable name changes, we should conform to the corefx coding standard.

**Comment by Youssef1313** [comment]
> 
> 
> Yes, there is no wrong convention. But I want to match the convention of [the overview article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties) and other property articles([using](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties), [interface](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/interface-properties) and [restricting accessor](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility)).
> 
> So how about modifying other 3 articles?

By **correct**, I really meant the convention used in corefx (Also ReSharper follows it), @rumaniel

**Comment by BillWagner** [comment]
@rumaniel Are you going to create a related PR in dotnet/docs to update the article where these snippets are used? I think we've reached agreement on the naming conventions to use. We do need to ensure the article text matches the sample.

**Comment by rumaniel** [comment]
Sorry for the late comments. I will update this PR and docs.

**Comment by rumaniel** [comment]
I revert my origin commits and update other conventions with the corefx coding standards.

**Pull request merged**
