### PR TITLE
Delete a sample that is moved to dotnet/AspNetDocs

### PR DESCRIPTION
**Pull request by Youssef1313**
Addresses https://github.com/dotnet/samples/pull/3741#issuecomment-661224680

### CODE REVIEW

**Comment by Youssef1313** [comment]
@adegeo The build check didn't run here. Only CLA is run.

**Comment by adegeo** [comment]
I need to update the tools. Whoops.. brb

**Comment by Youssef1313** [comment]
@adegeo Are these tools open source? Curious to look how they're implemented 😄

**Comment by adegeo** [comment]
Just the processing logic of the LocateProjects tool is: https://github.com/dotnet/docs/tree/master/.github/workflows/dependencies

**Comment by adegeo** [comment]
OK well we'll improve the tool next go around with a nuget restore for visual studio projects and see if that fixes this one 😁 I'll leave this issue open.

**Comment by BillWagner** [comment]
closing and opening for a fresh CI build.

**Comment by BillWagner** [comment]
ping @adegeo 

It looks like we need to setup the machine correctly to restore packages for old-style builds. Can you take a look?

**Comment by adegeo** [comment]
@Youssef1313 @BillWagner 

OK Lots of testing here to figure this out. It seems that the project itself has this error built into it, which was leading us down the wrong path. Specifically it looks for a v1.0.0 of a nuget package and if it's not found, errors out.

It's also using an older version of visual studio and nuget references, which the normal visual studio (msbuild) is not automatically handling. You need to run `nuget.exe restore -PackagesDirectory ../packages` to get nuget packages downloaded. OR you need to keep the solution file as the old nuget package reference system coupled with nuget.exe runs automatically on the solution file without specifying a directory (`nuget.exe restore` while the current directory has the sln file).

The dependency bot upped the packages which ends up breaking the builds too. The newer versions of all these packages have changed enough that the interdependencies have changed quite a bit.

Considering the app is 2 years old, running framework, and was built on an older visual studio, this app needs modernization to make it build correctly.

@Rick-Anderson @scottaddie Is there a modern version of this MVC sample we can update to?

**Comment by Rick-Anderson** [comment]
I recommend retiring the sample and leaving the asp.net samples for us to update in https://github.com/dotnet/AspNetCore.Docs

**Comment by adegeo** [comment]
@Rick-Anderson Is there something in ASP.NET that we can retire this article for? I just noticed this is .NET Framework, not Core.

**Comment by Rick-Anderson** [comment]
It doesn't look like this sample belongs in this repo. From https://github.com/dotnet/samples/blob/master/README.md

> Those projects should build and run on the widest set of platforms possible for the given sample. In practice, that means building .NET Core-based console applications where possible. 

We should keep MVC samples in the https://github.com/dotnet/AspNetCore.Docs repo.

cc @scottaddie

**Comment by adegeo** [comment]
@Youssef1313 lets delete this sample. it's referenced in `samples-and-tutorials\index.md`

**Comment by Youssef1313** [comment]
@adegeo That will break aspnet docs too.
It's referenced in https://docs.microsoft.com/en-us/aspnet/mvc/overview/deployment/docker-aspnetmvc at the time of writing this.

**Comment by adegeo** [comment]
Whoops. I think I meant delete reference to this sample from https://github.com/dotnet/docs/tree/master/docs/samples-and-tutorials

@Rick-Anderson Do you guys want this sample? It's MVC for classic ASP.NET. Considering the docker tutorial for classic ASP.NET references this sample as something to download and use for migrating an app to docker, I would think you guys want that somewhere 😄

**Comment by Rick-Anderson** [comment]
I think there are plenty of ASP.NET 4.x docker samples. cc @scottaddie  if he thinks it's worth moving.

**Comment by scottaddie** [comment]
Please move this sample to the dotnet/AspNetDocs repo. It makes sense to keep the sample around since it's referenced by an ASP.NET 4.x doc.

**Comment by BillWagner** [comment]
@Youssef1313 I apologize for all the delays. Do you want to make the updates here, or should we start over?

**Comment by Youssef1313** [comment]
@BillWagner Should the sample be deleted from dotnet/samples and added to AspNetDocs docs?

**Comment by BillWagner** [comment]
> Should the sample be deleted from dotnet/samples and added to AspNetDocs docs (and where in the repo)?

@Youssef1313 Yes, that's where the discussion ended.

**Comment by Youssef1313** [comment]
@BillWagner I'm not sure where the sample should live in AspNetDocs repo

**Comment by BillWagner** [comment]
@Youssef1313 Let's ask @scottaddie

**Comment by Youssef1313** [comment]
Thanks @scottaddie 
I opened https://github.com/dotnet/AspNetDocs/pull/453 to add the sample and update the link in the article.
Also opened https://github.com/dotnet/docs/pull/20934 to delete the link to the deleted sample here.

**Review by scottaddie — APPROVED** [review]

**Comment by scottaddie** [comment]
Thank you for all your hard work here, @Youssef1313!

**Pull request merged**
