### PR TITLE
Remove blank lines

### PR DESCRIPTION
**Pull request by NextTurn**
Contributes to #1884 

Enforces rules [SA1507](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1507.md), [SA1517](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1517.md), [SA1518](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1518.md).

Adds byte order marks by the way.

Unless specified, files accessed by line are left untouched.

Future PRs might be smaller, but this one is quite trivial.

### CODE REVIEW

**Comment by NextTurn** [comment]
@BillWagner 

I did use the analyzers to automate the changes. Here is an unstable and buggy version of the tool:

https://gist.github.com/NextTurn/cbf4b1afc0deb7a7bfdf2761fe360c67

By replacing the `Id` string, it can be used with some other rules.

**Comment by Youssef1313** [comment]
@NextTurn, I noticed that a file was edited while it was specified in access-by-line file.

Your changes didn't affect the referenced lines, so I'm asking if that change was intended? If not, the files referenced by lines will need to be reviewed.

image

**Comment by NextTurn** [comment]
Every commit in this PR with "access by line" in message was manually reviewed.

**Comment by Youssef1313** [comment]
> 
> 
> Every commit in this PR with "access by line" in message was manually reviewed.

Oh I didn't notice the commit messages.

**Pull request merged**
