### PR TITLE
Fix product metadata

### PR DESCRIPTION
**Pull request by gewarren**
Fix metadata to get samples published. Valid product values are here: https://review.docs.microsoft.com/en-us/help/contribute/metadata-taxonomies?branch=master#product

### CODE REVIEW

**Comment by adegeo** [comment]
@gewarren this wasn't a problem previously. how do you differentiate dotnet-core from dotnet-framework?

**Comment by gewarren** [comment]
This PR may not be needed. They are working to reinstate dotnet-framework as a valid product value (see thread sent to .NET content team).

**Comment by gewarren** [comment]
This PR may not be needed. They are working to reinstate dotnet-framework as a valid product value (see thread sent to .NET content team).

**Comment by gewarren** [comment]
dotnet-framework has been added back as a valid value now, so I'm closing this PR.

**Pull request closed without merging**
