### PR TITLE
Add WCF samples

### PR DESCRIPTION
**Pull request by gewarren**
Samples were previously available on the download center. Related to #4672.

Contributes to dotnet/docs#24814.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

I'd like to have @adegeo take a look to see if we can address the build issue, but that's not necessary

**Comment by adegeo** [comment]
I think we can play around with some of this. I'll look at generating config files for each of the projects... brb

**Comment by adegeo** [comment]
@gewarren Merge https://github.com/gewarren/samples/pull/1 to add the snippet config files. I downloaded the snippets results output.json file to the root of the repo on my machine and used this powershell script to generate the files:

```powershell
$trimroot = "D:\a\samples\samples\"
$snippets_file = "snippets.5000.json"
$snippet_content = @"
{
    `"host`": `"visualstudio`"
}
"@

foreach ($item in (Get-Content .\output.json | ConvertFrom-Json | Select-Object ProjectFile)) {
  $folder = Split-Path ($item.ProjectFile.SubString($trimroot.Length)) | Resolve-Path
  
  Write-Host "Creating $(Join-Path $folder $snippets_file)"
  New-Item -Path $folder -Name $snippets_file -ItemType "file" -Value $snippet_content
  
}
```

**Comment by gewarren** [comment]
@adegeo Can you take another look? It looks like it's failing with the same error.

**Comment by adegeo** [comment]
The errors that remain seem to be one of two things:

01. Projects are referencing a path to VS v10:

    ```xml
    <Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" />
    ```
    The path should be `$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets` if it's not incompatible I mean. That at least is where the file exists on my computer

02. Four different database files are missing in the repo, MDF/LDF files, for example: `\framework\wcf\Basic\Binding\WS\TransactionFlow\VB\service\SampleDb_log.ldf` Can you recover those?

**Pull request merged**
