### PR TITLE
Make method name PascalCase

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by adegeo** [comment]
We don't need to change private members. I would probably just leave this alone since the author probably did it intentionally?

**Comment by Youssef1313** [comment]
Wondering why this could be done intentionally?
A small side question: where this sample actually used?

**Comment by adegeo** [comment]
"samples" here are supposed to be downloaded and run as examples, not referred to via the docs and "snippets" but to answer your question, it's a typical styling to not use PascalCase on private members.

**Comment by Youssef1313** [comment]
I personally didn't see the camelCase for private methods styling before, but I'm okay too with closing if you prefer to keep it camelCase.

**Comment by adegeo** [comment]
I'd prefer not to change anything that isn't critical 😄 If someone is redoing the whole sample and wants to use a different style for private, that's fine.

Thanks though 😄 😄

**Comment by adegeo** [comment]
Originally the framework design guidelines don't cover private. Private is only to you, the programmer, and not to any publish consumers of your app/library, so there aren't any set guidelines.

**Pull request closed without merging**
