### PR TITLE
Re-generate dependabot config file

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
A question unrelated to the PR:

when the snippets were moved to docs, did the unused files get deleted? or there still unused files in the snippets folder in dotnet/docs?

**Comment by Thraka** [comment]
@Youssef1313 Yes. It didn't delete unused files though, it deleted folders which had no reference to them or their subfolders. It was not only moved to dotnet/docs but also into the api docs repo. So the snippets were split in two.

**Comment by Youssef1313** [comment]
> It didn't delete unused files though, it deleted folders which had no reference to them or their subfolders.

Aren't the unused files the files which had no reference?

**Comment by Youssef1313** [comment]
@BillWagner, I wrote a tool to regenerate it, the idea is just similar than the tool you linked to.
Check https://github.com/dotnet/samples/pull/1874 for its code.

**Pull request merged**
