### PR TITLE
Added SkipLast and TakeLast examples

### PR DESCRIPTION
**Pull request by tomzorz**
See Snippet203 and Snippet204

## Summary

Describe your changes here.

Part of the fix for dotnet/dotnet-api-docs/issues/2267, dotnet/dotnet-api-docs/issues/1060 and dotnet/dotnet-api-docs/issues/1061.

### CODE REVIEW

**Comment by tomzorz** [comment]
@rpetrusha I'll add the VB samples, and yes I was - see https://github.com/dotnet/dotnet-api-docs/issues/2267 for details.

**Comment by tomzorz** [comment]
@rpetrusha I added the vb samples. (I followed the pattern of the other examples in the file.)

**Comment by BillWagner** [comment]
@rpetrusha This is ready for a final review. All changes have been addressed.

**Comment by rpetrusha** [comment]
Thanks for adding the Visual Basic example, @tomzorz. I'll merge your PR now. The changes will be live on docs.microsoft.com sometime next week.

**Comment by tomzorz** [comment]
Excellent, thank you!

**Pull request merged**
