### PR TITLE
typo: Obect -> Object

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by BillWagner** [comment]
@nschonni These all LGTM

However, before I merge it, is there a corresponding PR in dotnet/docs? If not, we should wait to merge this. I'm afraid that changing the snippet names would create build errors.

**Comment by nschonni** [comment]
No, there are no hits in dotnet/docs. Unless it's used somewhere else, they may be orphan examples

**Comment by rpetrusha** [comment]
The code can also be used in dotntet/dotnet-api-docs.

**Comment by nschonni** [comment]
No hits in dotntet/dotnet-api-docs either

**Comment by rpetrusha** [comment]
If not only the snippets but the source code files generally aren't used in their docs or dotnet-api-docs, I wonder whether we should delete them rather than fix typos. What do you think, @BillWagner?

**Comment by BillWagner** [comment]
I was wondering the same thing @rpetrusha 

I think it would be better to remove samples that aren't used.

**Comment by nschonni** [comment]
PS: I did a quick github search over on the MicrosoftDocs and Aspnet (since it owns Entity Framework), but didn't get hits either.
Feel free to close this if you want to delete the examples instead

**Comment by BillWagner** [comment]
Thanks @nschonni 

I'll close this, and open a new PR to remove the affected files.

**Pull request closed without merging**
